### ISSUE TITLE
Вопрос по 13 ячейке в ноутбуке

### ISSUE THREAD

**Issue by LinkaG** [ShT3ch/Data-Fusion-2023-Atack#1]
Добрый день!
А можно спросить по вот этому моменту 
![image](https://user-images.githubusercontent.com/39047437/227519620-a30317af-301d-46db-865d-6c71dba509a4.png)
я так понимаю, что тут выпилена какая-то штука интересная?

**Comment by ShT3ch** [comment]
Доброго. :)

Это следы не сработавшей гипотезы (или частично сработавшей). Дело в том, что в исходной статье меняют по одному элементу за раз N раз. Я вместо этого один раз меняю N элементов. Если в этом цикле поставить 10, а в бюджете прописать 1, то теоретически результат будет лучше, но не факт, что модель выберет именно 10 разных транзакций для изменения.

Я решил, что лучше наверняка за раз поменять 10 транзакций, чем 10 раз менять по одной.

**Comment by LinkaG** [comment]
Спасибо большое за ответ!
